// Millage rates — Allegheny County, PA ONLY.
// This app is scoped exclusively to Allegheny County; the county-level baseline
// millage and assessment constants live in tax.js (AlleghenyTax).
// muniMills/schoolMills are mills applied to ASSESSED value.
// Data re-sourced 2026-07-17 from the county's live millage pages
// (apps.alleghenycounty.us/website/MillMuni.asp = municipal mills,
// MillSD.asp = school mills), covering all 128 in-county municipalities.
// Quaker Valley school rate overridden to QVSD's certified 2026-27 figure
// (22.8469 mills) since the county page still posts the 2025-26 rate.
// McDonald Borough and Trafford Borough are excluded because their school
// districts lie outside Allegheny County.
// School rates reflect the county's currently-posted certifications and
// should be refreshed each July as districts adopt new budgets.
// County baseline mills (6.43, effective 2025) live in tax.js, not here.

const MILLAGE_DATA = [
  { region: "CENTRAL / CITY", muni: "City of Pittsburgh", school: "Pittsburgh Public", muniMills: 8.06, schoolMills: 10.25, eitDefault: 3 },
  { region: "CENTRAL / CITY", muni: "Mount Oliver Borough", school: "Pittsburgh Public", muniMills: 16.5, schoolMills: 10.25 },
  { region: "NORTH", muni: "Aleppo Township", school: "Quaker Valley", muniMills: 3.5, schoolMills: 22.8469 },
  { region: "NORTH", muni: "Avalon Borough", school: "Northgate", muniMills: 9.83, schoolMills: 29.8584 },
  { region: "NORTH", muni: "Bell Acres Borough", school: "Quaker Valley", muniMills: 4.82, schoolMills: 22.8469 },
  { region: "NORTH", muni: "Bellevue Borough", school: "Northgate", muniMills: 5.89, schoolMills: 29.8584 },
  { region: "NORTH", muni: "Ben Avon Borough", school: "Avonworth", muniMills: 5.5, schoolMills: 22.28 },
  { region: "NORTH", muni: "Ben Avon Heights Borough", school: "Avonworth", muniMills: 7.95, schoolMills: 22.28 },
  { region: "NORTH", muni: "Brackenridge Borough", school: "Highlands", muniMills: 7, schoolMills: 25.13 },
  { region: "NORTH", muni: "Bradford Woods Borough", school: "North Allegheny", muniMills: 3.375, schoolMills: 19.74 },
  { region: "NORTH", muni: "East Deer Township", school: "Deer Lakes", muniMills: 4.65, schoolMills: 24.25 },
  { region: "NORTH", muni: "Edgeworth Borough", school: "Quaker Valley", muniMills: 4.15, schoolMills: 22.8469 },
  { region: "NORTH", muni: "Emsworth Borough", school: "Avonworth", muniMills: 5.955, schoolMills: 22.28 },
  { region: "NORTH", muni: "Etna Borough", school: "Shaler Area", muniMills: 9.5, schoolMills: 26.3391 },
  { region: "NORTH", muni: "Fawn Township", school: "Highlands", muniMills: 3.04, schoolMills: 25.13 },
  { region: "NORTH", muni: "Franklin Park Borough", school: "North Allegheny", muniMills: 1.59, schoolMills: 19.74 },
  { region: "NORTH", muni: "Frazer Township", school: "Deer Lakes", muniMills: 3.5, schoolMills: 24.25 },
  { region: "NORTH", muni: "Glen Osborne Borough", school: "Quaker Valley", muniMills: 4.9, schoolMills: 22.8469 },
  { region: "NORTH", muni: "Glenfield Borough", school: "Quaker Valley", muniMills: 4.15, schoolMills: 22.8469 },
  { region: "NORTH", muni: "Hampton Township", school: "Hampton", muniMills: 2.9241, schoolMills: 23.92 },
  { region: "NORTH", muni: "Harrison Township", school: "Highlands", muniMills: 5.606, schoolMills: 25.13 },
  { region: "NORTH", muni: "Haysville Borough", school: "Quaker Valley", muniMills: 6.063, schoolMills: 22.8469 },
  { region: "NORTH", muni: "Kilbuck Township", school: "Avonworth", muniMills: 3.79, schoolMills: 22.28 },
  { region: "NORTH", muni: "Leet Township", school: "Quaker Valley", muniMills: 9.1, schoolMills: 22.8469 },
  { region: "NORTH", muni: "Leetsdale Borough", school: "Quaker Valley", muniMills: 9, schoolMills: 22.8469 },
  { region: "NORTH", muni: "Marshall Township", school: "North Allegheny", muniMills: 1.42, schoolMills: 19.74 },
  { region: "NORTH", muni: "McCandless Township", school: "North Allegheny", muniMills: 1.236, schoolMills: 19.74 },
  { region: "NORTH", muni: "Millvale Borough", school: "Shaler Area", muniMills: 9.5, schoolMills: 26.3391 },
  { region: "NORTH", muni: "Ohio Township", school: "Avonworth", muniMills: 3.69, schoolMills: 22.28 },
  { region: "NORTH", muni: "Pine Township", school: "Pine-Richland", muniMills: 0.998, schoolMills: 19.5867 },
  { region: "NORTH", muni: "Reserve Township", school: "Shaler Area", muniMills: 6.47, schoolMills: 26.3391 },
  { region: "NORTH", muni: "Richland Township", school: "Pine-Richland", muniMills: 2.69, schoolMills: 19.5867 },
  { region: "NORTH", muni: "Ross Township", school: "North Hills", muniMills: 3.7, schoolMills: 20.37 },
  { region: "NORTH", muni: "Sewickley Borough", school: "Quaker Valley", muniMills: 6.25, schoolMills: 22.8469 },
  { region: "NORTH", muni: "Sewickley Heights Borough", school: "Quaker Valley", muniMills: 5.5, schoolMills: 22.8469 },
  { region: "NORTH", muni: "Sewickley Hills Borough", school: "Quaker Valley", muniMills: 2.84, schoolMills: 22.8469 },
  { region: "NORTH", muni: "Shaler Township", school: "Shaler Area", muniMills: 3.49, schoolMills: 26.3391 },
  { region: "NORTH", muni: "Tarentum Borough", school: "Highlands", muniMills: 5.98, schoolMills: 25.13 },
  { region: "NORTH", muni: "West Deer Township", school: "Deer Lakes", muniMills: 2.9, schoolMills: 24.25 },
  { region: "NORTH", muni: "West View Borough", school: "North Hills", muniMills: 6.3, schoolMills: 20.37 },
  { region: "SOUTH", muni: "Baldwin Borough", school: "Baldwin-Whitehall", muniMills: 8.03, schoolMills: 25 },
  { region: "SOUTH", muni: "Baldwin Township", school: "Baldwin-Whitehall", muniMills: 9.8, schoolMills: 25 },
  { region: "SOUTH", muni: "Bethel Park", school: "Bethel Park", muniMills: 3.53, schoolMills: 27.3263 },
  { region: "SOUTH", muni: "Brentwood Borough", school: "Brentwood", muniMills: 10, schoolMills: 39.1977 },
  { region: "SOUTH", muni: "Bridgeville Borough", school: "Chartiers Valley", muniMills: 8.25, schoolMills: 20.1909 },
  { region: "SOUTH", muni: "Castle Shannon Borough", school: "Keystone Oaks", muniMills: 12.158, schoolMills: 21.9442 },
  { region: "SOUTH", muni: "Collier Township", school: "Chartiers Valley", muniMills: 3.7, schoolMills: 20.1909 },
  { region: "SOUTH", muni: "Dormont Borough", school: "Keystone Oaks", muniMills: 10.97, schoolMills: 21.9442 },
  { region: "SOUTH", muni: "Green Tree Borough", school: "Keystone Oaks", muniMills: 4.61, schoolMills: 21.9442 },
  { region: "SOUTH", muni: "Heidelberg Borough", school: "Chartiers Valley", muniMills: 9.45, schoolMills: 20.1909 },
  { region: "SOUTH", muni: "Jefferson Hills Borough", school: "West Jefferson", muniMills: 5.66, schoolMills: 24.947 },
  { region: "SOUTH", muni: "Mount Lebanon", school: "Mt. Lebanon", muniMills: 4.5, schoolMills: 30.95 },
  { region: "SOUTH", muni: "Pleasant Hills Borough", school: "West Jefferson", muniMills: 11.5, schoolMills: 24.947 },
  { region: "SOUTH", muni: "Scott Township", school: "Chartiers Valley", muniMills: 7.9741, schoolMills: 20.1909 },
  { region: "SOUTH", muni: "South Fayette Township", school: "South Fayette", muniMills: 5.98, schoolMills: 27.7 },
  { region: "SOUTH", muni: "South Park Township", school: "South Park", muniMills: 3.062, schoolMills: 28.98 },
  { region: "SOUTH", muni: "Upper St. Clair Township", school: "Upper St. Clair", muniMills: 3.83, schoolMills: 31.515 },
  { region: "SOUTH", muni: "West Elizabeth Borough", school: "West Jefferson", muniMills: 4.55, schoolMills: 24.947 },
  { region: "SOUTH", muni: "Whitehall Borough", school: "Baldwin-Whitehall", muniMills: 5.42, schoolMills: 25 },
  { region: "EAST", muni: "Aspinwall Borough", school: "Fox Chapel Area", muniMills: 8.36, schoolMills: 22.0076 },
  { region: "EAST", muni: "Blawnox Borough", school: "Fox Chapel Area", muniMills: 10.85, schoolMills: 22.0076 },
  { region: "EAST", muni: "Braddock Borough", school: "Woodland Hills", muniMills: 13.65, schoolMills: 27.83 },
  { region: "EAST", muni: "Braddock Hills Borough", school: "Woodland Hills", muniMills: 9.4, schoolMills: 27.83 },
  { region: "EAST", muni: "Chalfant Borough", school: "Woodland Hills", muniMills: 8.9, schoolMills: 27.83 },
  { region: "EAST", muni: "Cheswick Borough", school: "Allegheny Valley", muniMills: 5.85, schoolMills: 21.7049 },
  { region: "EAST", muni: "Churchill Borough", school: "Woodland Hills", muniMills: 9, schoolMills: 27.83 },
  { region: "EAST", muni: "East McKeesport Borough", school: "East Allegheny", muniMills: 12.4, schoolMills: 28.024 },
  { region: "EAST", muni: "East Pittsburgh Borough", school: "Woodland Hills", muniMills: 13.45, schoolMills: 27.83 },
  { region: "EAST", muni: "Edgewood Borough", school: "Woodland Hills", muniMills: 7.185, schoolMills: 27.83 },
  { region: "EAST", muni: "Forest Hills Borough", school: "Woodland Hills", muniMills: 8.75, schoolMills: 27.83 },
  { region: "EAST", muni: "Fox Chapel Borough", school: "Fox Chapel Area", muniMills: 2.95, schoolMills: 22.0076 },
  { region: "EAST", muni: "Harmar Township", school: "Allegheny Valley", muniMills: 3.15, schoolMills: 21.7049 },
  { region: "EAST", muni: "Indiana Township", school: "Fox Chapel Area", muniMills: 3.47, schoolMills: 22.0076 },
  { region: "EAST", muni: "Monroeville Municipality", school: "Gateway", muniMills: 5.5, schoolMills: 25.2718 },
  { region: "EAST", muni: "North Braddock Borough", school: "Woodland Hills", muniMills: 12.5, schoolMills: 27.83 },
  { region: "EAST", muni: "North Versailles Township", school: "East Allegheny", muniMills: 7.75, schoolMills: 28.024 },
  { region: "EAST", muni: "O'Hara Township", school: "Fox Chapel Area", muniMills: 2.4, schoolMills: 22.0076 },
  { region: "EAST", muni: "Oakmont Borough", school: "Riverview", muniMills: 4.95, schoolMills: 25.5 },
  { region: "EAST", muni: "Penn Hills Township", school: "Penn Hills", muniMills: 6.944, schoolMills: 31.5965 },
  { region: "EAST", muni: "Pitcairn Borough", school: "Gateway", muniMills: 10.25, schoolMills: 25.2718 },
  { region: "EAST", muni: "Plum Borough", school: "Plum", muniMills: 6.63, schoolMills: 23.9159 },
  { region: "EAST", muni: "Rankin Borough", school: "Woodland Hills", muniMills: 11.6928, schoolMills: 27.83 },
  { region: "EAST", muni: "Sharpsburg Borough", school: "Fox Chapel Area", muniMills: 9.75, schoolMills: 22.0076 },
  { region: "EAST", muni: "Springdale Borough", school: "Allegheny Valley", muniMills: 9.75, schoolMills: 21.7049 },
  { region: "EAST", muni: "Springdale Township", school: "Allegheny Valley", muniMills: 9.5, schoolMills: 21.7049 },
  { region: "EAST", muni: "Swissvale Borough", school: "Woodland Hills", muniMills: 9, schoolMills: 27.83 },
  { region: "EAST", muni: "Turtle Creek Borough", school: "Woodland Hills", muniMills: 10, schoolMills: 27.83 },
  { region: "EAST", muni: "Verona Borough", school: "Riverview", muniMills: 10.7, schoolMills: 25.5 },
  { region: "EAST", muni: "Wall Borough", school: "East Allegheny", muniMills: 9, schoolMills: 28.024 },
  { region: "EAST", muni: "Wilkins Township", school: "Woodland Hills", muniMills: 7.174, schoolMills: 27.83 },
  { region: "EAST", muni: "Wilkinsburg Borough", school: "Wilkinsburg", muniMills: 14, schoolMills: 27.6301 },
  { region: "EAST", muni: "Wilmerding Borough", school: "East Allegheny", muniMills: 13, schoolMills: 28.024 },
  { region: "WEST", muni: "Carnegie Borough", school: "Carlynton", muniMills: 8, schoolMills: 28.5082 },
  { region: "WEST", muni: "Coraopolis Borough", school: "Cornell", muniMills: 12.5, schoolMills: 27.8317 },
  { region: "WEST", muni: "Crafton Borough", school: "Carlynton", muniMills: 8.59, schoolMills: 28.5082 },
  { region: "WEST", muni: "Crescent Township", school: "Moon Area", muniMills: 8.4, schoolMills: 25.2831 },
  { region: "WEST", muni: "Findlay Township", school: "West Allegheny", muniMills: 1.6, schoolMills: 18.51 },
  { region: "WEST", muni: "Ingram Borough", school: "Montour", muniMills: 6.4, schoolMills: 17.9638 },
  { region: "WEST", muni: "Kennedy Township", school: "Montour", muniMills: 2.5, schoolMills: 17.9638 },
  { region: "WEST", muni: "McKees Rocks Borough", school: "Sto-Rox", muniMills: 9.4, schoolMills: 31.7837 },
  { region: "WEST", muni: "Moon Township", school: "Moon Area", muniMills: 2.74, schoolMills: 25.2831 },
  { region: "WEST", muni: "Neville Township", school: "Cornell", muniMills: 5.2917, schoolMills: 27.8317 },
  { region: "WEST", muni: "North Fayette Township", school: "West Allegheny", muniMills: 3.29, schoolMills: 18.51 },
  { region: "WEST", muni: "Oakdale Borough", school: "West Allegheny", muniMills: 5, schoolMills: 18.51 },
  { region: "WEST", muni: "Pennsbury Village", school: "Montour", muniMills: 6.8, schoolMills: 17.9638 },
  { region: "WEST", muni: "Robinson Township", school: "Montour", muniMills: 3.2, schoolMills: 17.9638 },
  { region: "WEST", muni: "Rosslyn Farms Borough", school: "Carlynton", muniMills: 8, schoolMills: 28.5082 },
  { region: "WEST", muni: "Stowe Township", school: "Sto-Rox", muniMills: 10.48, schoolMills: 31.7837 },
  { region: "WEST", muni: "Thornburg Borough", school: "Montour", muniMills: 6.6, schoolMills: 17.9638 },
  // Clairton levies SPLIT land/building rates (municipal land 35.0, school land 105.7527 per county pages);
  // this app models the building rates only, so Clairton estimates are approximate.
  { region: "MON VALLEY", muni: "City of Clairton", school: "Clairton City", muniMills: 3.5, schoolMills: 10.0 },
  { region: "MON VALLEY", muni: "City of Duquesne", school: "Duquesne Area", muniMills: 20, schoolMills: 22.58 },
  { region: "MON VALLEY", muni: "City of McKeesport", school: "McKeesport Area", muniMills: 20.5, schoolMills: 20.96 },
  { region: "MON VALLEY", muni: "Dravosburg Borough", school: "McKeesport Area", muniMills: 8.55, schoolMills: 20.96 },
  { region: "MON VALLEY", muni: "Elizabeth Borough", school: "Elizabeth-Forward", muniMills: 10, schoolMills: 28.3544 },
  { region: "MON VALLEY", muni: "Elizabeth Township", school: "Elizabeth-Forward", muniMills: 4.026, schoolMills: 28.3544 },
  { region: "MON VALLEY", muni: "Forward Township", school: "Elizabeth-Forward", muniMills: 1, schoolMills: 28.3544 },
  { region: "MON VALLEY", muni: "Glassport Borough", school: "South Allegheny", muniMills: 17.49, schoolMills: 28.5 },
  { region: "MON VALLEY", muni: "Homestead Borough", school: "Steel Valley", muniMills: 15.33, schoolMills: 31.3546 },
  { region: "MON VALLEY", muni: "Liberty Borough", school: "South Allegheny", muniMills: 8, schoolMills: 28.5 },
  { region: "MON VALLEY", muni: "Lincoln Borough", school: "South Allegheny", muniMills: 10, schoolMills: 28.5 },
  { region: "MON VALLEY", muni: "Munhall Borough", school: "Steel Valley", muniMills: 13.92, schoolMills: 31.3546 },
  { region: "MON VALLEY", muni: "Port Vue Borough", school: "South Allegheny", muniMills: 8.4, schoolMills: 28.5 },
  { region: "MON VALLEY", muni: "South Versailles Township", school: "McKeesport Area", muniMills: 2.9, schoolMills: 20.96 },
  { region: "MON VALLEY", muni: "Versailles Borough", school: "McKeesport Area", muniMills: 8, schoolMills: 20.96 },
  { region: "MON VALLEY", muni: "West Homestead Borough", school: "Steel Valley", muniMills: 11.75, schoolMills: 31.3546 },
  { region: "MON VALLEY", muni: "West Mifflin Borough", school: "West Mifflin Area", muniMills: 10.53, schoolMills: 27.2771 },
  { region: "MON VALLEY", muni: "Whitaker Borough", school: "West Mifflin Area", muniMills: 12.5, schoolMills: 27.2771 },
  { region: "MON VALLEY", muni: "White Oak Borough", school: "McKeesport Area", muniMills: 9, schoolMills: 20.96 },
];
